[package]
name = "voxel_engine_prototype"
version = "0.1.0"
authors = ["LokiVKlokeNaAndoke <ma.ba1@rambler.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
amethyst = "0.13.2"
float-cmp = "0.5.3"
bitflags = "1.2.1"
log = "0.4.8"
fern = "0.5.9"
lazy_static = "1.4.0"
chrono = "0.4.10"
num-traits = "0.2.11"

[features]
default = ["vulkan"]
vulkan = ["amethyst/vulkan"]

[profile.dev]
opt-level = 2

[profile.release]
lto = true