[package]
name = "voxel_engine_prototype"
version = "0.1.0"
authors = ["LokiVKlokeNaAndoke <ma.ba1@rambler.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
amethyst = "0.15.0"
bitflags = "1.2.1"
log = "0.4.11"
lazy_static = "1.4.0"
chrono = "0.4.13"
ndarray = "0.13.1"

[features]
default = ["vulkan"]
vulkan = ["amethyst/vulkan"]

[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 0

[profile.release]
lto = true