level_filter = "DEBUG"
module_levels = [
    [
        "amethyst",
        "INFO",
    ],
    [
        "amethyst_assets",
        "INFO",
    ],
    [
        "distill_daemon",
        "INFO",
    ],
    [
        "winit",
        "INFO",
    ],
    [
        "amethyst_rendy",
        "INFO",
    ],
    [
        "distill_loader",
        "INFO",
    ],
    [
        "amethyst_controls",
        "INFO",
    ],
    [
        "amethyst_ui",
        "INFO",
    ],
    [
        "rendy_chain",
        "INFO",
    ],
    [
        "amethyst_core",
        "INFO",
    ],
    [
        "voxel_engine_prototype_lib::voxels::systems::chunk_per_frame_system",
        "info",
    ],
    [
        "voxel_engine_prototype_lib::voxels::systems::chunk_render",
        "info",
    ],
    [
        "amethyst_utils::fps_counter",
        "info",
    ],
]
