on: [push, pull_request]

name: CI

jobs:
  check:
    name: Check, clippy, fmt
    runs-on: ubuntu-latest
    steps:
      - name: install linux deps
        run: |
          sudo apt update
          sudo apt install -y gcc pkg-config openssl libasound2-dev cmake build-essential python3 libfreetype6-dev libexpat1-dev libxcb-composite0-dev libssl-dev libx11-dev pulseaudio libudev
      - uses: actions/checkout@master
      - uses: actions-rs/toolchain@master
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt, clippy

      - name: Run cargo check
        uses: actions-rs/cargo@master
        with:
          command: check
      
      - name: Run cargo clippy
        uses: actions-rs/cargo@master
        with:
          command: clippy
          
      - name: Run cargo test
        uses: actions-rs/cargo@master
        with:
          command: test 
          
      - name: Run cargo fmt
        uses: actions-rs/cargo@master
        with:
          command: fmt
          args: -- --check
    
